package repository

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/eusebioleite/selfin/database"
	"github.com/eusebioleite/selfin/models"
	"github.com/eusebioleite/selfin/utils"
)

type Category = models.Category

// GetCategories returns all categories from database
func GetCategories() ([]Category, error) {
	// 1. initializes an empty category struct
	var categories []Category

	// 2. get rows from database
	query := `
	SELECT
		id,
		description
	FROM categories
	ORDER BY id DESC
	`
	rows, err := database.DB.Query(query)
	if err != nil {
		return categories, fmt.Errorf("Error obtaining categories -> %w", err)
	}
	defer rows.Close()

	// 3. loads the category struct
	for rows.Next() {
		var c Category
		if err := rows.Scan(&c.ID, &c.Description); err != nil {
			return categories, fmt.Errorf("Error obtaining categories -> %w", err)
		}
		categories = append(categories, c)
	}

	return categories, nil
}

// GetCategory returns a category by id
func GetCategory(id int64) (Category, error) {
	// 1. initializes empty struct
	var category Category

	// 2. get row from database
	query := `
	SELECT
		id,
		description
	FROM categories
	WHERE id = ?
	ORDER BY id DESC
	`
	err := database.DB.QueryRow(query, id).
		Scan(&category.ID, &category.Description)
	if err != nil {
		if err == sql.ErrNoRows {
			return category, errors.New("category not found.")
		} else {
			return category, errors.New("Error obtaining category.")
		}
	}

	return category, nil
}

// NewCategory creates a new category.
// this function receives a category struct and returns the struct with the id returned by the database
func NewCategory(category *Category) error {

	// 1. executes the insert query with values from the struct provided
	query := `
	INSERT INTO categories (description)
	VALUES (?)
	`
	res, err := database.DB.Exec(query, category.Description)
	if err != nil {
		return fmt.Errorf("Error creating new category -> %w", err)
	}

	// 2. gets the id generated by the database
	id, err := res.LastInsertId()
	if err != nil {
		return fmt.Errorf("Error obtaining 'id' generated for category -> %w", err)
	}

	// 3. updates the struct with the id
	category.ID = id

	return nil
}

// UpdateCategory updates a category.
func UpdateCategory(category *Category) error {

	// 1. checks if an id was sent
	if category.ID == 0 {
		return errors.New("no ID was provided")
	}

	// 2. builds the update query
	query := "UPDATE categories SET "
	var args []any

	// 2.1. checks if a description was sent
	if category.Description != "" {
		query += "description = ?, "
		args = append(args, category.Description)
	}

	// 3. checks if any field was sent at all
	if len(args) == 0 {
		return nil
	}

	// 4. removes the last comma
	query = strings.TrimSuffix(query, ", ")

	// 5. adds the where clause
	query += " WHERE id = ?"
	args = append(args, category.ID)

	// 6. executes the query
	_, err := database.DB.Exec(query, args...)
	if err != nil {
		return fmt.Errorf("Error updating category -> %w", err)
	}
	/* 7. checks if any row was updated at all
	if !utils.HasRowsAffected(res) {
		log.Logger.Warn().Int64("category_id", category.ID).Msg("No rows affected.")
	}*/

	return nil
}

func DeleteCategory(id int64) error {
	// 1. checks if an id was sent at all
	if id == 0 {
		return errors.New("no ID was provided")
	}

	// 2. executes the delete query
	_, err := database.DB.Exec(
		"DELETE FROM categories where id = ?", id)
	if err != nil {
		if utils.IsConstraintViolation(err) {
			return errors.New("category is in use by one or more transactions")
		}
		return fmt.Errorf("Error deleting category -> %w", err)
	}

	/* 3. checks if any row was deleted at all
	if !utils.HasRowsAffected(res) {
		log.Logger.Warn().Int64("category_id", id).Msg("No rows affected.")
	}*/

	return nil
}
