package repository

import (
	"database/sql"
	"errors"
	"net/http"
	"strings"

	"github.com/eusebioleite/selfin/database"
	"github.com/eusebioleite/selfin/models"
	"github.com/eusebioleite/selfin/utils"
	"github.com/rs/zerolog/log"
)

type Transaction = models.Transaction

// GetTransactions returns all transactions from database
func GetTransactions() ([]Transaction, error) {
	// 1. initializes an empty transaction struct
	var transactions []Transaction

	// 2. get rows from database
	query := `
	SELECT
		id,
		date,
		amount,
		type,
		description,
		transaction_id,
		user_id
	FROM transactions
	ORDER BY id DESC
	`
	rows, err := database.DB.Query(query)
	if err != nil {
		log.Logger.Error().Int("error_code", http.StatusInternalServerError).Msg("Error obtaining transactions.")
		return transactions, err
	}
	defer rows.Close()

	// 3. loads the transaction struct
	for rows.Next() {
		var c Transaction
		if err := rows.Scan(&c.ID, &c.Description); err != nil {
			log.Logger.Error().Int("error_code", http.StatusInternalServerError).Msg("Error parsing transactions.")
			return transactions, err
		}
		transactions = append(transactions, c)
	}

	return transactions, nil
}

// GetTransaction returns a transaction by id
func GetTransaction(id int64) (Transaction, error) {
	// 1. initializes empty struct
	var transaction Transaction

	// 2. get row from database
	query := `
	SELECT
		id,
		date,
		amount,
		type,
		description,
		transaction_id,
		user_id
	FROM transactions
	ORDER BY id DESC
	WHERE id = ?
	`
	err := database.DB.QueryRow(query, id).
		Scan(&transaction.ID, &transaction.Description)
	if err != nil {
		if err == sql.ErrNoRows {
			log.Logger.Error().
				Int("error_code", http.StatusNotFound).
				Err(err).
				Msg("transaction not found.")
			return transaction, errors.New("transaction not found.")
		} else {
			log.Logger.Error().
				Int("error_code", http.StatusInternalServerError).
				Err(err).
				Msg("Error obtaining transaction.")
			return transaction, errors.New("Error obtaining transaction.")
		}
	}

	return transaction, nil
}

// NewTransaction creates a new transaction.
// this function receives a transaction struct and returns the struct with the id returned by the database
func NewTransaction(transaction *Transaction) error {

	// 1. executes the insert query with values from the struct provided
	query := `
	INSERT INTO transactions (description)
	VALUES (?, ?, ?)
	`
	res, err := database.DB.Exec(query, transaction.Description)
	if err != nil {
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Err(err).
			Msg("Error creating new transaction.")
		return err
	}

	// 2. gets the id generated by the database
	id, err := res.LastInsertId()
	if err != nil {
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Err(err).
			Msg("Error obtaining 'id' generated for transaction.")
		return err
	}

	// 3. updates the struct with the id
	transaction.ID = id

	return nil
}

// UpdateTransaction updates a transaction.
func UpdateTransaction(transaction *Transaction) error {

	// 1. checks if an id was sent
	if transaction.ID == 0 {
		log.Logger.Error().
			Int("error_code", http.StatusBadRequest).
			Int64("transaction_id", transaction.ID).
			Msg("No ID was provided.")
		return errors.New("no ID was provided")
	}

	// 2. builds the update query
	query := "UPDATE transactions SET "
	var args []any

	// 2.1. checks if a description was sent
	if transaction.Description != "" {
		query += "description = ?, "
		args = append(args, transaction.Description)
	}

	// 3. checks if any field was sent at all
	if len(args) == 0 {
		log.Logger.Warn().Int64("transaction_id", transaction.ID).Msg("No fields to update.")
		return nil
	}

	// 4. removes the last comma
	query = strings.TrimSuffix(query, ", ")

	// 5. adds the where clause
	query += " WHERE id = ?"
	args = append(args, transaction.ID)

	// 6. executes the query
	res, err := database.DB.Exec(query, args)

	// 7. checks if any row was updated at all
	rows, err := res.RowsAffected()
	if err != nil {
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Err(err).
			Msg("Error checking if transaction was updated.")
		return err
	}
	if rows == 0 {
		log.Logger.Warn().Int64("transaction_id", transaction.ID).Msg("No rows affected.")
	}

	return nil
}

func DeleteTransaction(id int64) error {
	// 1. checks if an id was sent at all
	if id == 0 {
		log.Logger.Error().
			Int("error_code", http.StatusBadRequest).
			Int64("transaction_id", id).
			Msg("No ID was provided.")
		return errors.New("no ID was provided")
	}

	// 2. executes the delete query
	query := `
	DELETE FROM transactions
	WHERE id = ?
	`
	res, err := database.DB.Exec(query, id)
	if err != nil {
		if utils.IsConstraintViolation(err) {
			log.Logger.Error().
				Int("error_code", http.StatusConflict).
				Int64("transaction_id", id).
				Err(err).
				Msg("Cannot delete transaction: it is referenced by one or more transactions.")
			return errors.New("transaction is in use by one or more transactions")
		}
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Int64("transaction_id", id).
			Err(err).
			Msg("Error deleting transaction.")
		return err
	}

	// 3. checks if any row was deleted at all
	if !utils.HasRowsAffected(res) {
		log.Logger.Warn().Int64("transaction_id", id).Msg("No rows affected.")
	}

	return nil
}
