package repository

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/eusebioleite/selfin/database"
	"github.com/eusebioleite/selfin/models"
	"github.com/eusebioleite/selfin/utils"
)

type Transaction = models.Transaction

// GetTransactions returns all transactions from database
func GetTransactions() ([]Transaction, error) {
	// 1. initializes an empty transaction struct
	var transactions []Transaction

	// 2. get rows from database
	query := `
	SELECT
		id,
		date,
		amount,
		type,
		description,
		category_id
		user_id
	FROM transactions
	ORDER BY id DESC
	`
	rows, err := database.DB.Query(query)
	if err != nil {
		return transactions, fmt.Errorf("Error obtaining transactions -> %w", err)
	}
	defer rows.Close()

	// 3. loads the transaction struct
	for rows.Next() {
		var t Transaction
		if err := rows.Scan(&t.ID, &t.Date, &t.Amount, &t.Type, &t.Description, &t.CategoryID, &t.UserID); err != nil {
			return transactions, fmt.Errorf("Error parsing users -> %w", err)
		}
		transactions = append(transactions, t)
	}

	return transactions, nil
}

// GetTransaction returns a transaction by id
func GetTransaction(id int64) (Transaction, error) {
	// 1. initializes empty struct
	var transaction Transaction

	// 2. get row from database
	query := `
	SELECT
		id,
		date,
		amount,
		type,
		description,
		category_id,
		user_id
	FROM transactions
	WHERE id = ?
	ORDER BY id DESC
	`
	err := database.DB.QueryRow(query, id).
		Scan(&transaction.ID, &transaction.Date, &transaction.Amount, &transaction.Type, &transaction.Description, &transaction.CategoryID, &transaction.UserID)
	if err != nil {
		if err == sql.ErrNoRows {
			return transaction, errors.New("transaction not found.")
		} else {
			return transaction, errors.New("Error obtaining transaction.")
		}
	}

	return transaction, nil
}

// NewTransaction creates a new transaction.
// this function receives a transaction struct and returns the struct with the id returned by the database
func NewTransaction(transaction *Transaction) error {

	// 1. executes the insert query with values from the struct provided
	query := `
	INSERT INTO transactions (date, amount, type, description, category_id, user_id)
	VALUES (?, ?, ?, ?, ?, ?)
	`
	res, err := database.DB.Exec(query, transaction.Date, transaction.Amount, transaction.Type, transaction.Description, transaction.CategoryID, transaction.UserID)
	if err != nil {
		return fmt.Errorf("Error creating transaction -> %w", err)
	}

	// 2. gets the id generated by the database
	id, err := res.LastInsertId()
	if err != nil {
		return fmt.Errorf("Error getting generated transaction id-> %w", err)
	}

	// 3. updates the struct with the id
	transaction.ID = id

	return nil
}

// UpdateTransaction updates a transaction.
func UpdateTransaction(transaction *Transaction) error {

	// 1. checks if an id was sent
	if transaction.ID == 0 {
		return errors.New("no ID was provided")
	}

	// 2. builds the update query and proceeds to build a dynamic string
	query := "UPDATE transactions SET "
	var args []any

	if transaction.Date != "" {
		query += "date = ?, "
		args = append(args, transaction.Date)
	}

	if transaction.Amount > 0 {
		query += "amount= ?, "
		args = append(args, transaction.Amount)
	}

	if transaction.Type != "" {
		query += "type = ?, "
		args = append(args, transaction.Type)
	}

	if transaction.CategoryID > 0 {
		query += "category_id = ?, "
		args = append(args, transaction.CategoryID)
	}

	if transaction.UserID > 0 {
		query += "user_id= ?, "
		args = append(args, transaction.UserID)
	}

	// 3. checks if any field was sent at all
	if len(args) == 0 {
		return nil
	}

	// 4. removes the last comma
	query = strings.TrimSuffix(query, ", ")

	// 5. adds the where clause
	query += " WHERE id = ?"
	args = append(args, transaction.ID)

	// 6. executes the query
	_, err := database.DB.Exec(query, args...)
	if err != nil {
		return fmt.Errorf("Error updating transaction -> %w", err)
	}

	return nil
}

func DeleteTransaction(id int64) error {
	// 1. checks if an id was sent at all
	if id == 0 {
		return errors.New("no ID was provided")
	}

	// 2. executes the delete query
	query := `
	DELETE FROM transactions
	WHERE id = ?
	`
	_, err := database.DB.Exec(query, id)
	if err != nil {
		if utils.IsConstraintViolation(err) {
			return errors.New("Cannot delete transaction -> transaction is in use by one or more transactions")
		}
		return fmt.Errorf("Error deleting transaction -> %w", err)
	}

	return nil
}
