package repository

import (
	"database/sql"
	"errors"
	"net/http"
	"strings"

	"github.com/eusebioleite/selfin/database"
	"github.com/eusebioleite/selfin/models"
	"github.com/eusebioleite/selfin/utils"
	"github.com/rs/zerolog/log"
)

type User = models.User

// GetUsers returns all users from database
func GetUsers() ([]User, error) {
	// 1. initializes an empty user struct
	var users []User

	// 2. get rows from database
	query := `
		SELECT
			id,
			name,
			login,
			password
		FROM users
		ORDER BY id DESC
		`
	rows, err := database.DB.Query(query)
	if err != nil {
		log.Logger.Error().Int("error_code", http.StatusInternalServerError).Msg("Error obtaining users.")
		return users, err
	}
	defer rows.Close()

	// 3. loads the user struct
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Login, &u.Password); err != nil {
			log.Logger.Error().Int("error_code", http.StatusInternalServerError).Msg("Error parsing users.")
			return users, err
		}
		users = append(users, u)
	}

	return users, nil
}

// GetUser returns a user by id
func GetUser(id int64) (User, error) {
	// 1. initializes empty struct
	var user User

	// 2. get row from database
	query := `
		SELECT
			id,
			name,
			login,
			password
		FROM users
		WHERE id = ?
		ORDER BY id DESC
		`
	err := database.DB.QueryRow(query, id).
		Scan(&user.ID, &user.Name, &user.Login, &user.Password)
	if err != nil {
		if err == sql.ErrNoRows {
			log.Logger.Error().
				Int("error_code", http.StatusNotFound).
				Err(err).
				Msg("User not found.")
			return user, errors.New("User not found.")
		} else {
			log.Logger.Error().
				Int("error_code", http.StatusInternalServerError).
				Err(err).
				Msg("Error obtaining user.")
			return user, errors.New("Error obtaining user.")
		}
	}

	return user, nil
}

// GetUser returns a user by login
func GetUserByLogin(login string) (User, error) {
	// 1. initializes empty struct
	var user User

	// 2. get row from database
	query := `
		SELECT
			id,
			name,
			login,
			password
		FROM users
		WHERE login = ?
		ORDER BY id DESC
		`
	err := database.DB.QueryRow(query, login).
		Scan(&user.ID, &user.Name, &user.Login, &user.Password)
	if err != nil {
		if err == sql.ErrNoRows {
			log.Logger.Error().
				Int("error_code", http.StatusUnauthorized).
				Err(err).
				Msg("User not found.")
			return user, errors.New("User not found.")
		} else {
			log.Logger.Error().
				Int("error_code", http.StatusInternalServerError).
				Err(err).
				Msg("Error obtaining user.")
			return user, errors.New("Error obtaining user.")
		}
	}

	return user, nil
}

// NewUser creates a new user.
// this function receives a user struct and returns the struct with the id returned by the database
func NewUser(user *User) error {

	// 1. executes the insert query with values from the struct provided
	query := `
	INSERT INTO users (name, login, password)
	VALUES (?, ?, ?)
	`
	res, err := database.DB.Exec(query, user.Name, user.Login, user.Password)
	if err != nil {
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Err(err).
			Msg("Error creating new user.")
		return err
	}

	// 2. gets the id generated by the database
	id, err := res.LastInsertId()
	if err != nil {
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Err(err).
			Msg("Error obtaining 'id' generated for user.")
		return err
	}

	// 3. updates the struct with the id
	user.ID = id

	return nil
}

// UpdateUser updates a user.
func UpdateUser(user *User) error {

	// 1. checks if an id was sent
	if user.ID == 0 {
		log.Logger.Error().
			Int("error_code", http.StatusBadRequest).
			Int64("user_id", user.ID).
			Msg("No ID was provided.")
		return errors.New("no ID was provided")
	}

	// 2. builds the update query
	query := "UPDATE users SET "
	var args []any

	// 2.1. checks if a name was sent
	if user.Name != "" {
		query += "name = ?, "
		args = append(args, user.Name)
	}

	// 2.2. checks if a login was sent
	if user.Login != "" {
		query += "login = ?, "
		args = append(args, user.Login)
	}

	// 2.3. checks if a password was sent
	if user.Password != "" {
		query += "password = ?, "
		args = append(args, user.Password)
	}

	// 3. checks if any field was sent at all
	if len(args) == 0 {
		log.Logger.Warn().Int64("user_id", user.ID).Msg("No fields to update.")
		return nil
	}

	// 4. removes the last comma
	query = strings.TrimSuffix(query, ", ")

	// 5. adds the where clause
	query += " WHERE id = ?"
	args = append(args, user.ID)

	// 6. executes the query
	res, err := database.DB.Exec(query, args)

	// 7. checks if any row was updated at all
	rows, err := res.RowsAffected()
	if err != nil {
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Err(err).
			Msg("Error checking if user was updated.")
		return err
	}
	if rows == 0 {
		log.Logger.Warn().Int64("user_id", user.ID).Msg("No rows affected.")
	}

	return nil
}

func DeleteUser(id int64) error {
	// 1. checks if an id was sent at all
	if id == 0 {
		log.Logger.Error().
			Int("error_code", http.StatusBadRequest).
			Int64("user_id", id).
			Msg("No ID was provided.")
		return errors.New("no ID was provided")
	}

	// 2. executes the delete query
	query := `
	DELETE FROM users
	WHERE id = ?
	`
	res, err := database.DB.Exec(query, id)
	if err != nil {
		if utils.IsConstraintViolation(err) {
			log.Logger.Error().
				Int("error_code", http.StatusConflict).
				Int64("user_id", id).
				Err(err).
				Msg("Cannot delete user: it is referenced by one or more transactions.")
			return errors.New("user is in use by one or more transactions")
		}
		log.Logger.Error().
			Int("error_code", http.StatusInternalServerError).
			Int64("user_id", id).
			Err(err).
			Msg("Error deleting user.")
		return err
	}

	// 3. checks if any row was deleted at all
	if !utils.HasRowsAffected(res) {
		log.Logger.Warn().Int64("user_id", id).Msg("No rows affected.")
	}

	return nil
}
