package repository

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/eusebioleite/selfin/database"
	"github.com/eusebioleite/selfin/models"
	"github.com/eusebioleite/selfin/utils"
)

type User = models.User

// GetUsers returns all users from database
func GetUsers() ([]User, error) {
	// 1. initializes an empty user struct
	var users []User

	// 2. get rows from database
	query := `
		SELECT
			id,
			name,
			login,
			password
		FROM users
		ORDER BY id DESC
		`
	rows, err := database.DB.Query(query)
	if err != nil {
		return users, fmt.Errorf("Error obtaining users -> %w", err)
	}
	defer rows.Close()

	// 3. loads the user struct
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Login, &u.Password); err != nil {
			return users, fmt.Errorf("Error parsing users -> %w", err)
		}
		users = append(users, u)
	}

	return users, nil
}

// GetUser returns a user by id
func GetUser(id int64) (User, error) {
	// 1. initializes empty struct
	var user User

	// 2. get row from database
	query := `
		SELECT
			id,
			name,
			login,
			password
		FROM users
		WHERE id = ?
		ORDER BY id DESC
		`
	err := database.DB.QueryRow(query, id).
		Scan(&user.ID, &user.Name, &user.Login, &user.Password)
	if err != nil {
		if err == sql.ErrNoRows {
			return user, errors.New("User not found.")
		} else {
			return user, errors.New("Error obtaining user.")
		}
	}

	return user, nil
}

// GetUser returns a user by login
func GetUserByLogin(login string) (User, error) {
	// 1. initializes empty struct
	var user User

	// 2. get row from database
	query := `
		SELECT
			id,
			name,
			login,
			password
		FROM users
		WHERE login = ?
		ORDER BY id DESC
		`
	err := database.DB.QueryRow(query, login).
		Scan(&user.ID, &user.Name, &user.Login, &user.Password)
	if err != nil {
		if err == sql.ErrNoRows {
			return user, errors.New("User not found.")
		} else {
			return user, errors.New("Error obtaining user.")
		}
	}

	return user, nil
}

// NewUser creates a new user.
// this function receives a user struct and returns the struct with the id returned by the database
func NewUser(user *User) error {

	// 1. executes the insert query with values from the struct provided
	query := `
	INSERT INTO users (name, login, password)
	VALUES (?, ?, ?)
	`
	res, err := database.DB.Exec(query, user.Name, user.Login, user.Password)
	if err != nil {
		return fmt.Errorf("Error creating new user -> %w", err)
	}

	// 2. gets the id generated by the database
	id, err := res.LastInsertId()
	if err != nil {
		return fmt.Errorf("Error obtaining 'id' generated for user -> %w", err)
	}

	// 3. updates the struct with the id
	user.ID = id

	return nil
}

// UpdateUser updates a user.
func UpdateUser(user *User) error {

	// 1. checks if an id was sent
	if user.ID == 0 {
		return errors.New("no ID was provided")
	}

	// 2. builds the update query
	query := "UPDATE users SET "
	var args []any

	// 2.1. checks if a name was sent
	if user.Name != "" {
		query += "name = ?, "
		args = append(args, user.Name)
	}

	// 2.2. checks if a login was sent
	if user.Login != "" {
		query += "login = ?, "
		args = append(args, user.Login)
	}

	// 2.3. checks if a password was sent
	if user.Password != "" {
		query += "password = ?, "
		args = append(args, user.Password)
	}

	// 3. checks if any field was sent at all
	if len(args) == 0 {
		return nil
	}

	// 4. removes the last comma
	query = strings.TrimSuffix(query, ", ")

	// 5. adds the where clause
	query += " WHERE id = ?"
	args = append(args, user.ID)

	// 6. executes the query
	_, err := database.DB.Exec(query, args...)
	if err != nil {
		return fmt.Errorf("error updating user -> %w", err)
	}

	return nil
}

func DeleteUser(id int64) error {
	// 1. checks if an id was sent at all
	if id == 0 {
		return errors.New("no ID was provided")
	}

	// 2. executes the delete query
	query := `
	DELETE FROM users
	WHERE id = ?
	`
	_, err := database.DB.Exec(query, id)
	if err != nil {
		if utils.IsConstraintViolation(err) {
			return errors.New("Cannot delete user -> user is in use by one or more transactions")
		}
		return fmt.Errorf("Error deleting user -> %w", err)
	}

	return nil
}
