// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package base

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func App(content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head title=\"Selfin\"><script>\r\n\t\t\t\tdocument.addEventListener('alpine:init', () => {\r\n\t\t\t\t\tAlpine.data('appShell', () => ({\r\n\t\t\t\t\t\tmodalOpen: false,\r\n\t\t\t\t\t\topenModal() {\r\n\t\t\t\t\t\t\tthis.modalOpen = true;\r\n\t\t\t\t\t\t},\r\n\t\t\t\t\t\tcloseModal() {\r\n\t\t\t\t\t\t\tthis.modalOpen = false;\r\n\t\t\t\t\t\t\tsetTimeout(() => {\r\n\t\t\t\t\t\t\t\tif (!this.modalOpen) {\r\n\t\t\t\t\t\t\t\t\tconst content = document.getElementById('modal-content');\r\n\t\t\t\t\t\t\t\t\tif (content) content.innerHTML = '';\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t}, 300);\r\n\t\t\t\t\t\t},\r\n\t\t\t\t\t}));\r\n\t\t\t\t});\r\n\r\n\t\t\tdocument.addEventListener('htmx:afterSwap', (e) => {\r\n\t\t\t\t\tif (e.detail.target.id === 'modal-content') {\r\n\t\t\t\t\t\tAlpine.initTree(e.detail.target);\r\n\t\t\t\t\t\twindow.dispatchEvent(new CustomEvent('open-modal'));\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\r\n\t\t\t\tdocument.addEventListener('htmx:afterRequest', (e) => {\r\n\t\t\t\t\tif (e.detail.successful && e.detail.elt.closest('#modal-content form')) {\r\n\t\t\t\t\t\twindow.dispatchEvent(new CustomEvent('close-modal'));\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\r\n\t\t\t</script><script src=\"/resources/htmx.min.js\"></script><script src=\"/resources/alpine.min.js\"></script><script src=\"/resources/json-enc.js\"></script><link rel=\"stylesheet\" href=\"/resources/styles/main.css\"></head><body class=\"w-screen h-screen bg-neutral-950\" x-data=\"appShell()\" x-on:keydown.escape.window=\"closeModal()\" x-on:open-modal.window=\"openModal()\" x-on:close-modal.window=\"closeModal()\"><div class=\"h-full flex flex-row\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Menu().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main class=\"flex-1 h-full overflow-y-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></div><div x-show=\"modalOpen\" class=\"fixed inset-0 z-50 flex items-center justify-center\" style=\"display: none;\"><div class=\"absolute inset-0 bg-black/70\" x-show=\"modalOpen\" x-transition:enter=\"transition-opacity ease-out duration-300\" x-transition:enter-start=\"opacity-0\" x-transition:enter-end=\"opacity-100\" x-transition:leave=\"transition-opacity ease-in duration-300\" x-transition:leave-start=\"opacity-100\" x-transition:leave-end=\"opacity-0\" x-on:click=\"closeModal()\"></div><div id=\"modal-content\" x-show=\"modalOpen\" x-transition:enter=\"transition-all ease-out duration-300\" x-transition:enter-start=\"opacity-0 scale-95\" x-transition:enter-end=\"opacity-100 scale-100\" x-transition:leave=\"transition-all ease-in duration-300\" x-transition:leave-start=\"opacity-100 scale-100\" x-transition:leave-end=\"opacity-0 scale-95\" x-on:click.stop class=\"relative bg-neutral-900 border border-neutral-800 w-full max-w-2xl p-6 rounded-sm shadow-2xl z-10\"></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
