PRAGMA FOREIGN_KEYS = ON;

PRAGMA JOURNAL_MODE = WAL;

PRAGMA SYNCHRONOUS = NORMAL;

PRAGMA CACHE_SIZE = -64000;

PRAGMA TEMP_STORE = MEMORY;

PRAGMA READ_UNCOMMITTED = TRUE;

CREATE TABLE IF NOT EXISTS
    USERS (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        login TEXT NOT NULL UNIQUE,
        password TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS
    SESSIONS (
        id TEXT PRIMARY KEY NOT NULL,
        user_id INTEGER NOT NULL,
        expires_at TEXT NOT NULL,
        created_at TEXT DEFAULT (DATETIME('NOW', 'LOCALTIME')),
        FOREIGN KEY (USER_ID) REFERENCES USERS (id) ON DELETE CASCADE
    ) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS
    CATEGORIES (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        description TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS
    TRANSACTIONS (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL DEFAULT (STRFTIME('%D/%M/%Y', 'NOW')),
        amount INT NOT NULL DEFAULT 0,
        type TEXT NOT NULL DEFAULT 'Despesa',
        description TEXT NOT NULL,
        category_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        FOREIGN KEY (category_id) REFERENCES CATEGORIES (id),
        FOREIGN KEY (user_id) REFERENCES USERS (id)
    );

CREATE INDEX IF NOT EXISTS idx_transactions_user_login ON USERS (login);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON SESSIONS (user_id);

CREATE INDEX IF NOT EXISTS idx_transactions_category_id ON TRANSACTIONS (category_id);

CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON TRANSACTIONS (user_id);

CREATE INDEX IF NOT EXISTS idx_transactions_user_category_date ON TRANSACTIONS (user_id, category_id, date);

CREATE INDEX IF NOT EXISTS idx_transactions_user_amount ON TRANSACTIONS (user_id, amount);